# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dual_arm_msgs/Arm_Pose_Euler.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Arm_Pose_Euler(genpy.Message):
  _md5sum = "14cf69e90ba61a0c7ae2933996244f58"
  _type = "dual_arm_msgs/Arm_Pose_Euler"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 Px
float32 Py
float32 Pz
float32 Rx
float32 Ry
float32 Rz
"""
  __slots__ = ['Px','Py','Pz','Rx','Ry','Rz']
  _slot_types = ['float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Px,Py,Pz,Rx,Ry,Rz

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Arm_Pose_Euler, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.Px is None:
        self.Px = 0.
      if self.Py is None:
        self.Py = 0.
      if self.Pz is None:
        self.Pz = 0.
      if self.Rx is None:
        self.Rx = 0.
      if self.Ry is None:
        self.Ry = 0.
      if self.Rz is None:
        self.Rz = 0.
    else:
      self.Px = 0.
      self.Py = 0.
      self.Pz = 0.
      self.Rx = 0.
      self.Ry = 0.
      self.Rz = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.Px, _x.Py, _x.Pz, _x.Rx, _x.Ry, _x.Rz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.Px, _x.Py, _x.Pz, _x.Rx, _x.Ry, _x.Rz,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.Px, _x.Py, _x.Pz, _x.Rx, _x.Ry, _x.Rz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.Px, _x.Py, _x.Pz, _x.Rx, _x.Ry, _x.Rz,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
