// Generated by gencpp from file dual_arm_robot_demo/ObjectPose.msg
// DO NOT EDIT!


#ifndef DUAL_ARM_ROBOT_DEMO_MESSAGE_OBJECTPOSE_H
#define DUAL_ARM_ROBOT_DEMO_MESSAGE_OBJECTPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dual_arm_robot_demo
{
template <class ContainerAllocator>
struct ObjectPose_
{
  typedef ObjectPose_<ContainerAllocator> Type;

  ObjectPose_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  ObjectPose_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::dual_arm_robot_demo::ObjectPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dual_arm_robot_demo::ObjectPose_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectPose_

typedef ::dual_arm_robot_demo::ObjectPose_<std::allocator<void> > ObjectPose;

typedef boost::shared_ptr< ::dual_arm_robot_demo::ObjectPose > ObjectPosePtr;
typedef boost::shared_ptr< ::dual_arm_robot_demo::ObjectPose const> ObjectPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dual_arm_robot_demo::ObjectPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dual_arm_robot_demo::ObjectPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dual_arm_robot_demo::ObjectPose_<ContainerAllocator1> & lhs, const ::dual_arm_robot_demo::ObjectPose_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dual_arm_robot_demo::ObjectPose_<ContainerAllocator1> & lhs, const ::dual_arm_robot_demo::ObjectPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dual_arm_robot_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dual_arm_robot_demo::ObjectPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dual_arm_robot_demo::ObjectPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dual_arm_robot_demo::ObjectPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dual_arm_robot_demo::ObjectPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dual_arm_robot_demo::ObjectPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dual_arm_robot_demo::ObjectPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dual_arm_robot_demo::ObjectPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::dual_arm_robot_demo::ObjectPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a842b65f413084dULL;
  static const uint64_t static_value2 = 0xc2b10fb484ea7f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::dual_arm_robot_demo::ObjectPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dual_arm_robot_demo/ObjectPose";
  }

  static const char* value(const ::dual_arm_robot_demo::ObjectPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dual_arm_robot_demo::ObjectPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y \n"
"float64 z\n"
;
  }

  static const char* value(const ::dual_arm_robot_demo::ObjectPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dual_arm_robot_demo::ObjectPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dual_arm_robot_demo::ObjectPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dual_arm_robot_demo::ObjectPose_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUAL_ARM_ROBOT_DEMO_MESSAGE_OBJECTPOSE_H
