// Generated by gencpp from file servo_ros/ServoMove.msg
// DO NOT EDIT!


#ifndef SERVO_ROS_MESSAGE_SERVOMOVE_H
#define SERVO_ROS_MESSAGE_SERVOMOVE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servo_ros
{
template <class ContainerAllocator>
struct ServoMove_
{
  typedef ServoMove_<ContainerAllocator> Type;

  ServoMove_()
    : servo_id(0)
    , angle(0)
    , time(0)  {
    }
  ServoMove_(const ContainerAllocator& _alloc)
    : servo_id(0)
    , angle(0)
    , time(0)  {
  (void)_alloc;
    }



   typedef uint16_t _servo_id_type;
  _servo_id_type servo_id;

   typedef uint16_t _angle_type;
  _angle_type angle;

   typedef uint16_t _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::servo_ros::ServoMove_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servo_ros::ServoMove_<ContainerAllocator> const> ConstPtr;

}; // struct ServoMove_

typedef ::servo_ros::ServoMove_<std::allocator<void> > ServoMove;

typedef boost::shared_ptr< ::servo_ros::ServoMove > ServoMovePtr;
typedef boost::shared_ptr< ::servo_ros::ServoMove const> ServoMoveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servo_ros::ServoMove_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servo_ros::ServoMove_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::servo_ros::ServoMove_<ContainerAllocator1> & lhs, const ::servo_ros::ServoMove_<ContainerAllocator2> & rhs)
{
  return lhs.servo_id == rhs.servo_id &&
    lhs.angle == rhs.angle &&
    lhs.time == rhs.time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::servo_ros::ServoMove_<ContainerAllocator1> & lhs, const ::servo_ros::ServoMove_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace servo_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::servo_ros::ServoMove_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo_ros::ServoMove_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo_ros::ServoMove_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo_ros::ServoMove_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_ros::ServoMove_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_ros::ServoMove_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servo_ros::ServoMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fd942452571bdf83e3fa8f79a5e9a7d3";
  }

  static const char* value(const ::servo_ros::ServoMove_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfd942452571bdf83ULL;
  static const uint64_t static_value2 = 0xe3fa8f79a5e9a7d3ULL;
};

template<class ContainerAllocator>
struct DataType< ::servo_ros::ServoMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servo_ros/ServoMove";
  }

  static const char* value(const ::servo_ros::ServoMove_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servo_ros::ServoMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#舵机转动控制\n"
"uint16 servo_id	#舵机ID\n"
"uint16 angle	#角度位置0~1000\n"
"uint16 time     #运行时间(ms)\n"
;
  }

  static const char* value(const ::servo_ros::ServoMove_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servo_ros::ServoMove_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.servo_id);
      stream.next(m.angle);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoMove_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servo_ros::ServoMove_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servo_ros::ServoMove_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "servo_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.servo_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angle: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.angle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "time: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVO_ROS_MESSAGE_SERVOMOVE_H
