// Generated by gencpp from file servo_ros/ServoAngle.msg
// DO NOT EDIT!


#ifndef SERVO_ROS_MESSAGE_SERVOANGLE_H
#define SERVO_ROS_MESSAGE_SERVOANGLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servo_ros
{
template <class ContainerAllocator>
struct ServoAngle_
{
  typedef ServoAngle_<ContainerAllocator> Type;

  ServoAngle_()
    : servo_id_1(0)
    , angle_1(0)
    , servo_id_2(0)
    , angle_2(0)  {
    }
  ServoAngle_(const ContainerAllocator& _alloc)
    : servo_id_1(0)
    , angle_1(0)
    , servo_id_2(0)
    , angle_2(0)  {
  (void)_alloc;
    }



   typedef uint16_t _servo_id_1_type;
  _servo_id_1_type servo_id_1;

   typedef uint16_t _angle_1_type;
  _angle_1_type angle_1;

   typedef uint16_t _servo_id_2_type;
  _servo_id_2_type servo_id_2;

   typedef uint16_t _angle_2_type;
  _angle_2_type angle_2;





  typedef boost::shared_ptr< ::servo_ros::ServoAngle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servo_ros::ServoAngle_<ContainerAllocator> const> ConstPtr;

}; // struct ServoAngle_

typedef ::servo_ros::ServoAngle_<std::allocator<void> > ServoAngle;

typedef boost::shared_ptr< ::servo_ros::ServoAngle > ServoAnglePtr;
typedef boost::shared_ptr< ::servo_ros::ServoAngle const> ServoAngleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servo_ros::ServoAngle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servo_ros::ServoAngle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::servo_ros::ServoAngle_<ContainerAllocator1> & lhs, const ::servo_ros::ServoAngle_<ContainerAllocator2> & rhs)
{
  return lhs.servo_id_1 == rhs.servo_id_1 &&
    lhs.angle_1 == rhs.angle_1 &&
    lhs.servo_id_2 == rhs.servo_id_2 &&
    lhs.angle_2 == rhs.angle_2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::servo_ros::ServoAngle_<ContainerAllocator1> & lhs, const ::servo_ros::ServoAngle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace servo_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::servo_ros::ServoAngle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo_ros::ServoAngle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo_ros::ServoAngle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo_ros::ServoAngle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_ros::ServoAngle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_ros::ServoAngle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servo_ros::ServoAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9a8103b4cee119f9447f2067818f6250";
  }

  static const char* value(const ::servo_ros::ServoAngle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9a8103b4cee119f9ULL;
  static const uint64_t static_value2 = 0x447f2067818f6250ULL;
};

template<class ContainerAllocator>
struct DataType< ::servo_ros::ServoAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servo_ros/ServoAngle";
  }

  static const char* value(const ::servo_ros::ServoAngle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servo_ros::ServoAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#舵机返回角度\n"
"uint16 servo_id_1	#舵机ID\n"
"uint16 angle_1	#角度位置0~1000\n"
"uint16 servo_id_2	#舵机ID\n"
"uint16 angle_2	#角度位置0~1000\n"
;
  }

  static const char* value(const ::servo_ros::ServoAngle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servo_ros::ServoAngle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.servo_id_1);
      stream.next(m.angle_1);
      stream.next(m.servo_id_2);
      stream.next(m.angle_2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoAngle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servo_ros::ServoAngle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servo_ros::ServoAngle_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "servo_id_1: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.servo_id_1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angle_1: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.angle_1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "servo_id_2: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.servo_id_2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angle_2: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.angle_2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVO_ROS_MESSAGE_SERVOANGLE_H
