# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from servo_ros/ServoAngle.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ServoAngle(genpy.Message):
  _md5sum = "9a8103b4cee119f9447f2067818f6250"
  _type = "servo_ros/ServoAngle"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """#舵机返回角度
uint16 servo_id_1	#舵机ID
uint16 angle_1	#角度位置0~1000
uint16 servo_id_2	#舵机ID
uint16 angle_2	#角度位置0~1000
"""
  __slots__ = ['servo_id_1','angle_1','servo_id_2','angle_2']
  _slot_types = ['uint16','uint16','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       servo_id_1,angle_1,servo_id_2,angle_2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ServoAngle, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.servo_id_1 is None:
        self.servo_id_1 = 0
      if self.angle_1 is None:
        self.angle_1 = 0
      if self.servo_id_2 is None:
        self.servo_id_2 = 0
      if self.angle_2 is None:
        self.angle_2 = 0
    else:
      self.servo_id_1 = 0
      self.angle_1 = 0
      self.servo_id_2 = 0
      self.angle_2 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4H().pack(_x.servo_id_1, _x.angle_1, _x.servo_id_2, _x.angle_2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.servo_id_1, _x.angle_1, _x.servo_id_2, _x.angle_2,) = _get_struct_4H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4H().pack(_x.servo_id_1, _x.angle_1, _x.servo_id_2, _x.angle_2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.servo_id_1, _x.angle_1, _x.servo_id_2, _x.angle_2,) = _get_struct_4H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4H = None
def _get_struct_4H():
    global _struct_4H
    if _struct_4H is None:
        _struct_4H = struct.Struct("<4H")
    return _struct_4H
