// Generated by gencpp from file dual_arm_msgs/Arm_Pose_Euler.msg
// DO NOT EDIT!


#ifndef DUAL_ARM_MSGS_MESSAGE_ARM_POSE_EULER_H
#define DUAL_ARM_MSGS_MESSAGE_ARM_POSE_EULER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dual_arm_msgs
{
template <class ContainerAllocator>
struct Arm_Pose_Euler_
{
  typedef Arm_Pose_Euler_<ContainerAllocator> Type;

  Arm_Pose_Euler_()
    : Px(0.0)
    , Py(0.0)
    , Pz(0.0)
    , Rx(0.0)
    , Ry(0.0)
    , Rz(0.0)  {
    }
  Arm_Pose_Euler_(const ContainerAllocator& _alloc)
    : Px(0.0)
    , Py(0.0)
    , Pz(0.0)
    , Rx(0.0)
    , Ry(0.0)
    , Rz(0.0)  {
  (void)_alloc;
    }



   typedef float _Px_type;
  _Px_type Px;

   typedef float _Py_type;
  _Py_type Py;

   typedef float _Pz_type;
  _Pz_type Pz;

   typedef float _Rx_type;
  _Rx_type Rx;

   typedef float _Ry_type;
  _Ry_type Ry;

   typedef float _Rz_type;
  _Rz_type Rz;





  typedef boost::shared_ptr< ::dual_arm_msgs::Arm_Pose_Euler_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dual_arm_msgs::Arm_Pose_Euler_<ContainerAllocator> const> ConstPtr;

}; // struct Arm_Pose_Euler_

typedef ::dual_arm_msgs::Arm_Pose_Euler_<std::allocator<void> > Arm_Pose_Euler;

typedef boost::shared_ptr< ::dual_arm_msgs::Arm_Pose_Euler > Arm_Pose_EulerPtr;
typedef boost::shared_ptr< ::dual_arm_msgs::Arm_Pose_Euler const> Arm_Pose_EulerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dual_arm_msgs::Arm_Pose_Euler_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dual_arm_msgs::Arm_Pose_Euler_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dual_arm_msgs::Arm_Pose_Euler_<ContainerAllocator1> & lhs, const ::dual_arm_msgs::Arm_Pose_Euler_<ContainerAllocator2> & rhs)
{
  return lhs.Px == rhs.Px &&
    lhs.Py == rhs.Py &&
    lhs.Pz == rhs.Pz &&
    lhs.Rx == rhs.Rx &&
    lhs.Ry == rhs.Ry &&
    lhs.Rz == rhs.Rz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dual_arm_msgs::Arm_Pose_Euler_<ContainerAllocator1> & lhs, const ::dual_arm_msgs::Arm_Pose_Euler_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dual_arm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dual_arm_msgs::Arm_Pose_Euler_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dual_arm_msgs::Arm_Pose_Euler_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dual_arm_msgs::Arm_Pose_Euler_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dual_arm_msgs::Arm_Pose_Euler_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dual_arm_msgs::Arm_Pose_Euler_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dual_arm_msgs::Arm_Pose_Euler_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dual_arm_msgs::Arm_Pose_Euler_<ContainerAllocator> >
{
  static const char* value()
  {
    return "14cf69e90ba61a0c7ae2933996244f58";
  }

  static const char* value(const ::dual_arm_msgs::Arm_Pose_Euler_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x14cf69e90ba61a0cULL;
  static const uint64_t static_value2 = 0x7ae2933996244f58ULL;
};

template<class ContainerAllocator>
struct DataType< ::dual_arm_msgs::Arm_Pose_Euler_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dual_arm_msgs/Arm_Pose_Euler";
  }

  static const char* value(const ::dual_arm_msgs::Arm_Pose_Euler_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dual_arm_msgs::Arm_Pose_Euler_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 Px\n"
"float32 Py\n"
"float32 Pz\n"
"float32 Rx\n"
"float32 Ry\n"
"float32 Rz\n"
;
  }

  static const char* value(const ::dual_arm_msgs::Arm_Pose_Euler_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dual_arm_msgs::Arm_Pose_Euler_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Px);
      stream.next(m.Py);
      stream.next(m.Pz);
      stream.next(m.Rx);
      stream.next(m.Ry);
      stream.next(m.Rz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Arm_Pose_Euler_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dual_arm_msgs::Arm_Pose_Euler_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dual_arm_msgs::Arm_Pose_Euler_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "Px: ";
    Printer<float>::stream(s, indent + "  ", v.Px);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Py: ";
    Printer<float>::stream(s, indent + "  ", v.Py);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Pz: ";
    Printer<float>::stream(s, indent + "  ", v.Pz);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Rx: ";
    Printer<float>::stream(s, indent + "  ", v.Rx);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Ry: ";
    Printer<float>::stream(s, indent + "  ", v.Ry);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Rz: ";
    Printer<float>::stream(s, indent + "  ", v.Rz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUAL_ARM_MSGS_MESSAGE_ARM_POSE_EULER_H
