// Generated by gencpp from file dual_arm_msgs/Arm_Software_Version.msg
// DO NOT EDIT!


#ifndef DUAL_ARM_MSGS_MESSAGE_ARM_SOFTWARE_VERSION_H
#define DUAL_ARM_MSGS_MESSAGE_ARM_SOFTWARE_VERSION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dual_arm_msgs
{
template <class ContainerAllocator>
struct Arm_Software_Version_
{
  typedef Arm_Software_Version_<ContainerAllocator> Type;

  Arm_Software_Version_()
    : Product_version()
    , Plan_version()  {
    }
  Arm_Software_Version_(const ContainerAllocator& _alloc)
    : Product_version(_alloc)
    , Plan_version(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _Product_version_type;
  _Product_version_type Product_version;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _Plan_version_type;
  _Plan_version_type Plan_version;





  typedef boost::shared_ptr< ::dual_arm_msgs::Arm_Software_Version_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dual_arm_msgs::Arm_Software_Version_<ContainerAllocator> const> ConstPtr;

}; // struct Arm_Software_Version_

typedef ::dual_arm_msgs::Arm_Software_Version_<std::allocator<void> > Arm_Software_Version;

typedef boost::shared_ptr< ::dual_arm_msgs::Arm_Software_Version > Arm_Software_VersionPtr;
typedef boost::shared_ptr< ::dual_arm_msgs::Arm_Software_Version const> Arm_Software_VersionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dual_arm_msgs::Arm_Software_Version_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dual_arm_msgs::Arm_Software_Version_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dual_arm_msgs::Arm_Software_Version_<ContainerAllocator1> & lhs, const ::dual_arm_msgs::Arm_Software_Version_<ContainerAllocator2> & rhs)
{
  return lhs.Product_version == rhs.Product_version &&
    lhs.Plan_version == rhs.Plan_version;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dual_arm_msgs::Arm_Software_Version_<ContainerAllocator1> & lhs, const ::dual_arm_msgs::Arm_Software_Version_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dual_arm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dual_arm_msgs::Arm_Software_Version_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dual_arm_msgs::Arm_Software_Version_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dual_arm_msgs::Arm_Software_Version_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dual_arm_msgs::Arm_Software_Version_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dual_arm_msgs::Arm_Software_Version_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dual_arm_msgs::Arm_Software_Version_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dual_arm_msgs::Arm_Software_Version_<ContainerAllocator> >
{
  static const char* value()
  {
    return "875ac4a1506e782c8b37a03d7f6b51c9";
  }

  static const char* value(const ::dual_arm_msgs::Arm_Software_Version_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x875ac4a1506e782cULL;
  static const uint64_t static_value2 = 0x8b37a03d7f6b51c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::dual_arm_msgs::Arm_Software_Version_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dual_arm_msgs/Arm_Software_Version";
  }

  static const char* value(const ::dual_arm_msgs::Arm_Software_Version_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dual_arm_msgs::Arm_Software_Version_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Product_version\n"
"string Plan_version\n"
;
  }

  static const char* value(const ::dual_arm_msgs::Arm_Software_Version_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dual_arm_msgs::Arm_Software_Version_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Product_version);
      stream.next(m.Plan_version);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Arm_Software_Version_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dual_arm_msgs::Arm_Software_Version_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dual_arm_msgs::Arm_Software_Version_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "Product_version: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.Product_version);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Plan_version: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.Plan_version);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUAL_ARM_MSGS_MESSAGE_ARM_SOFTWARE_VERSION_H
