// Generated by gencpp from file dual_arm_msgs/CarteFdPose.msg
// DO NOT EDIT!


#ifndef DUAL_ARM_MSGS_MESSAGE_CARTEFDPOSE_H
#define DUAL_ARM_MSGS_MESSAGE_CARTEFDPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dual_arm_msgs
{
template <class ContainerAllocator>
struct CarteFdPose_
{
  typedef CarteFdPose_<ContainerAllocator> Type;

  CarteFdPose_()
    : Pose_Euler()  {
      Pose_Euler.assign(0.0);
  }
  CarteFdPose_(const ContainerAllocator& _alloc)
    : Pose_Euler()  {
  (void)_alloc;
      Pose_Euler.assign(0.0);
  }



   typedef boost::array<float, 6>  _Pose_Euler_type;
  _Pose_Euler_type Pose_Euler;





  typedef boost::shared_ptr< ::dual_arm_msgs::CarteFdPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dual_arm_msgs::CarteFdPose_<ContainerAllocator> const> ConstPtr;

}; // struct CarteFdPose_

typedef ::dual_arm_msgs::CarteFdPose_<std::allocator<void> > CarteFdPose;

typedef boost::shared_ptr< ::dual_arm_msgs::CarteFdPose > CarteFdPosePtr;
typedef boost::shared_ptr< ::dual_arm_msgs::CarteFdPose const> CarteFdPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dual_arm_msgs::CarteFdPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dual_arm_msgs::CarteFdPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dual_arm_msgs::CarteFdPose_<ContainerAllocator1> & lhs, const ::dual_arm_msgs::CarteFdPose_<ContainerAllocator2> & rhs)
{
  return lhs.Pose_Euler == rhs.Pose_Euler;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dual_arm_msgs::CarteFdPose_<ContainerAllocator1> & lhs, const ::dual_arm_msgs::CarteFdPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dual_arm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dual_arm_msgs::CarteFdPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dual_arm_msgs::CarteFdPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dual_arm_msgs::CarteFdPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dual_arm_msgs::CarteFdPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dual_arm_msgs::CarteFdPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dual_arm_msgs::CarteFdPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dual_arm_msgs::CarteFdPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "525ed60ead11361f867b19c646e09073";
  }

  static const char* value(const ::dual_arm_msgs::CarteFdPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x525ed60ead11361fULL;
  static const uint64_t static_value2 = 0x867b19c646e09073ULL;
};

template<class ContainerAllocator>
struct DataType< ::dual_arm_msgs::CarteFdPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dual_arm_msgs/CarteFdPose";
  }

  static const char* value(const ::dual_arm_msgs::CarteFdPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dual_arm_msgs::CarteFdPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[6] Pose_Euler\n"
;
  }

  static const char* value(const ::dual_arm_msgs::CarteFdPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dual_arm_msgs::CarteFdPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Pose_Euler);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarteFdPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dual_arm_msgs::CarteFdPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dual_arm_msgs::CarteFdPose_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "Pose_Euler: ";
    if (v.Pose_Euler.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.Pose_Euler.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.Pose_Euler[i]);
    }
    if (v.Pose_Euler.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUAL_ARM_MSGS_MESSAGE_CARTEFDPOSE_H
