// Generated by gencpp from file dual_arm_msgs/Servo_Move.msg
// DO NOT EDIT!


#ifndef DUAL_ARM_MSGS_MESSAGE_SERVO_MOVE_H
#define DUAL_ARM_MSGS_MESSAGE_SERVO_MOVE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dual_arm_msgs
{
template <class ContainerAllocator>
struct Servo_Move_
{
  typedef Servo_Move_<ContainerAllocator> Type;

  Servo_Move_()
    : servo_id(0)
    , angle(0)  {
    }
  Servo_Move_(const ContainerAllocator& _alloc)
    : servo_id(0)
    , angle(0)  {
  (void)_alloc;
    }



   typedef uint16_t _servo_id_type;
  _servo_id_type servo_id;

   typedef uint16_t _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::dual_arm_msgs::Servo_Move_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dual_arm_msgs::Servo_Move_<ContainerAllocator> const> ConstPtr;

}; // struct Servo_Move_

typedef ::dual_arm_msgs::Servo_Move_<std::allocator<void> > Servo_Move;

typedef boost::shared_ptr< ::dual_arm_msgs::Servo_Move > Servo_MovePtr;
typedef boost::shared_ptr< ::dual_arm_msgs::Servo_Move const> Servo_MoveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dual_arm_msgs::Servo_Move_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dual_arm_msgs::Servo_Move_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dual_arm_msgs::Servo_Move_<ContainerAllocator1> & lhs, const ::dual_arm_msgs::Servo_Move_<ContainerAllocator2> & rhs)
{
  return lhs.servo_id == rhs.servo_id &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dual_arm_msgs::Servo_Move_<ContainerAllocator1> & lhs, const ::dual_arm_msgs::Servo_Move_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dual_arm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dual_arm_msgs::Servo_Move_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dual_arm_msgs::Servo_Move_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dual_arm_msgs::Servo_Move_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dual_arm_msgs::Servo_Move_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dual_arm_msgs::Servo_Move_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dual_arm_msgs::Servo_Move_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dual_arm_msgs::Servo_Move_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b1ffad65c396de7e89b3adea80fcd0f";
  }

  static const char* value(const ::dual_arm_msgs::Servo_Move_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b1ffad65c396de7ULL;
  static const uint64_t static_value2 = 0xe89b3adea80fcd0fULL;
};

template<class ContainerAllocator>
struct DataType< ::dual_arm_msgs::Servo_Move_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dual_arm_msgs/Servo_Move";
  }

  static const char* value(const ::dual_arm_msgs::Servo_Move_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dual_arm_msgs::Servo_Move_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#舵机转动控制\n"
"uint16 servo_id	#舵机ID\n"
"uint16 angle	#角度位置0~1000\n"
;
  }

  static const char* value(const ::dual_arm_msgs::Servo_Move_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dual_arm_msgs::Servo_Move_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.servo_id);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Servo_Move_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dual_arm_msgs::Servo_Move_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dual_arm_msgs::Servo_Move_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "servo_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.servo_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angle: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUAL_ARM_MSGS_MESSAGE_SERVO_MOVE_H
